server:
  port: 80
# ==========applicationName===================
spring:
  application:
    name: cloud-payment-order
####Spring Cloud Consul for Service Discovery
cloud:
  consul:
    host: localhost
    port: 8500
    discovery:
      service-name: ${spring.application.name}